[package]

name = "pistoncore-event_loop"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "bfops",
]
tags = ["game", "event", "loop"]
description = "A generic event loop for games and interactive applications"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/event_loop.git"
homepage = "https://github.com/pistondevelopers/event_loop"

[lib]

name = "event_loop"
path = "src/lib.rs"

[dependencies]

pistoncore-current = "0.0.0"
time = "0.1.1"

